name: Artifact Demo

on: 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir output
          echo "This is a test file." > output/test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: output/
          retention-days: 7  # optional: default is 90 days
