name: Artifact Demo

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir output
          echo "This is a test file." > output/test.txt

      - name: Compress artifact
        run: |
          zip -r output.zip output/

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.1
          name: Release v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.0
          files: output.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
