name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
        
    - name: Upload built site
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: _site

    - name: Upload built site
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: _site

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        folder: _site
        branch: gh-pages
        commit-message: Deployment Successful...
          
